
version: 2

sources:
  - name: raw
    database: TRADESPHERE_DB
    schema: RAW
    tables:
      - name: RAW_ORDERS
      - name: RAW_RETURNS
      - name: RAW_COMPLAINTS
      - name: RAW_STORE_REGIONS